all:
	@make -j8 -C ./config
	@make -j8 -C ./pb
	@make -j8 -C ./common
	@make -j8 -C ./kernel
	@make -j8 -C ./data
	@make -j8 -C ./battle
	@make -j8 -C ./main
clean:
	@make -C ./config clean
	@make -C ./pb clean
	@make -C ./common clean
	@make -C ./kernel clean
	@make -C ./data clean
	@make -C ./battle clean
	@make -C ./main clean
