// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoActivity.proto

#ifndef PROTOBUF_ProtoActivity_2eproto__INCLUDED
#define PROTOBUF_ProtoActivity_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ProtoActivity {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtoActivity_2eproto();
void protobuf_AssignDesc_ProtoActivity_2eproto();
void protobuf_ShutdownFile_ProtoActivity_2eproto();

class GameAcitivityCPP;
class GameAcitivityAllCPP;

// ===================================================================

class GameAcitivityCPP : public ::google::protobuf::Message {
 public:
  GameAcitivityCPP();
  virtual ~GameAcitivityCPP();

  GameAcitivityCPP(const GameAcitivityCPP& from);

  inline GameAcitivityCPP& operator=(const GameAcitivityCPP& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameAcitivityCPP& default_instance();

  void Swap(GameAcitivityCPP* other);

  // implements Message ----------------------------------------------

  GameAcitivityCPP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameAcitivityCPP& from);
  void MergeFrom(const GameAcitivityCPP& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required uint32 version = 2;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 2;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // repeated uint32 actdata = 3;
  inline int actdata_size() const;
  inline void clear_actdata();
  static const int kActdataFieldNumber = 3;
  inline ::google::protobuf::uint32 actdata(int index) const;
  inline void set_actdata(int index, ::google::protobuf::uint32 value);
  inline void add_actdata(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      actdata() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_actdata();

  // @@protoc_insertion_point(class_scope:ProtoActivity.GameAcitivityCPP)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_version();
  inline void clear_has_version();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 version_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > actdata_;
  friend void  protobuf_AddDesc_ProtoActivity_2eproto();
  friend void protobuf_AssignDesc_ProtoActivity_2eproto();
  friend void protobuf_ShutdownFile_ProtoActivity_2eproto();

  void InitAsDefaultInstance();
  static GameAcitivityCPP* default_instance_;
};
// -------------------------------------------------------------------

class GameAcitivityAllCPP : public ::google::protobuf::Message {
 public:
  GameAcitivityAllCPP();
  virtual ~GameAcitivityAllCPP();

  GameAcitivityAllCPP(const GameAcitivityAllCPP& from);

  inline GameAcitivityAllCPP& operator=(const GameAcitivityAllCPP& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameAcitivityAllCPP& default_instance();

  void Swap(GameAcitivityAllCPP* other);

  // implements Message ----------------------------------------------

  GameAcitivityAllCPP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameAcitivityAllCPP& from);
  void MergeFrom(const GameAcitivityAllCPP& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ProtoActivity.GameAcitivityCPP activities = 1;
  inline int activities_size() const;
  inline void clear_activities();
  static const int kActivitiesFieldNumber = 1;
  inline const ::ProtoActivity::GameAcitivityCPP& activities(int index) const;
  inline ::ProtoActivity::GameAcitivityCPP* mutable_activities(int index);
  inline ::ProtoActivity::GameAcitivityCPP* add_activities();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoActivity::GameAcitivityCPP >&
      activities() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoActivity::GameAcitivityCPP >*
      mutable_activities();

  // @@protoc_insertion_point(class_scope:ProtoActivity.GameAcitivityAllCPP)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ProtoActivity::GameAcitivityCPP > activities_;
  friend void  protobuf_AddDesc_ProtoActivity_2eproto();
  friend void protobuf_AssignDesc_ProtoActivity_2eproto();
  friend void protobuf_ShutdownFile_ProtoActivity_2eproto();

  void InitAsDefaultInstance();
  static GameAcitivityAllCPP* default_instance_;
};
// ===================================================================


// ===================================================================

// GameAcitivityCPP

// required uint32 id = 1;
inline bool GameAcitivityCPP::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GameAcitivityCPP::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GameAcitivityCPP::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GameAcitivityCPP::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 GameAcitivityCPP::id() const {
  // @@protoc_insertion_point(field_get:ProtoActivity.GameAcitivityCPP.id)
  return id_;
}
inline void GameAcitivityCPP::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ProtoActivity.GameAcitivityCPP.id)
}

// required uint32 version = 2;
inline bool GameAcitivityCPP::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GameAcitivityCPP::set_has_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GameAcitivityCPP::clear_has_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GameAcitivityCPP::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 GameAcitivityCPP::version() const {
  // @@protoc_insertion_point(field_get:ProtoActivity.GameAcitivityCPP.version)
  return version_;
}
inline void GameAcitivityCPP::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:ProtoActivity.GameAcitivityCPP.version)
}

// repeated uint32 actdata = 3;
inline int GameAcitivityCPP::actdata_size() const {
  return actdata_.size();
}
inline void GameAcitivityCPP::clear_actdata() {
  actdata_.Clear();
}
inline ::google::protobuf::uint32 GameAcitivityCPP::actdata(int index) const {
  // @@protoc_insertion_point(field_get:ProtoActivity.GameAcitivityCPP.actdata)
  return actdata_.Get(index);
}
inline void GameAcitivityCPP::set_actdata(int index, ::google::protobuf::uint32 value) {
  actdata_.Set(index, value);
  // @@protoc_insertion_point(field_set:ProtoActivity.GameAcitivityCPP.actdata)
}
inline void GameAcitivityCPP::add_actdata(::google::protobuf::uint32 value) {
  actdata_.Add(value);
  // @@protoc_insertion_point(field_add:ProtoActivity.GameAcitivityCPP.actdata)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
GameAcitivityCPP::actdata() const {
  // @@protoc_insertion_point(field_list:ProtoActivity.GameAcitivityCPP.actdata)
  return actdata_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
GameAcitivityCPP::mutable_actdata() {
  // @@protoc_insertion_point(field_mutable_list:ProtoActivity.GameAcitivityCPP.actdata)
  return &actdata_;
}

// -------------------------------------------------------------------

// GameAcitivityAllCPP

// repeated .ProtoActivity.GameAcitivityCPP activities = 1;
inline int GameAcitivityAllCPP::activities_size() const {
  return activities_.size();
}
inline void GameAcitivityAllCPP::clear_activities() {
  activities_.Clear();
}
inline const ::ProtoActivity::GameAcitivityCPP& GameAcitivityAllCPP::activities(int index) const {
  // @@protoc_insertion_point(field_get:ProtoActivity.GameAcitivityAllCPP.activities)
  return activities_.Get(index);
}
inline ::ProtoActivity::GameAcitivityCPP* GameAcitivityAllCPP::mutable_activities(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoActivity.GameAcitivityAllCPP.activities)
  return activities_.Mutable(index);
}
inline ::ProtoActivity::GameAcitivityCPP* GameAcitivityAllCPP::add_activities() {
  // @@protoc_insertion_point(field_add:ProtoActivity.GameAcitivityAllCPP.activities)
  return activities_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoActivity::GameAcitivityCPP >&
GameAcitivityAllCPP::activities() const {
  // @@protoc_insertion_point(field_list:ProtoActivity.GameAcitivityAllCPP.activities)
  return activities_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoActivity::GameAcitivityCPP >*
GameAcitivityAllCPP::mutable_activities() {
  // @@protoc_insertion_point(field_mutable_list:ProtoActivity.GameAcitivityAllCPP.activities)
  return &activities_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoActivity

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtoActivity_2eproto__INCLUDED
