// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBuilding.proto

#ifndef PROTOBUF_ProtoBuilding_2eproto__INCLUDED
#define PROTOBUF_ProtoBuilding_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "DataCommon.pb.h"
#include "ProtoProduce.pb.h"
// @@protoc_insertion_point(includes)

namespace ProtoBuilding {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtoBuilding_2eproto();
void protobuf_AssignDesc_ProtoBuilding_2eproto();
void protobuf_ShutdownFile_ProtoBuilding_2eproto();

class BuildingCPP;
class EquipmentStarCPP;
class BuildReq;
class BuildResp;
class MoveReq;
class MoveResp;
class FlipReq;
class FlipResp;
class BuildingUpReq;
class BuildingUpResp;

// ===================================================================

class BuildingCPP : public ::google::protobuf::Message {
 public:
  BuildingCPP();
  virtual ~BuildingCPP();

  BuildingCPP(const BuildingCPP& from);

  inline BuildingCPP& operator=(const BuildingCPP& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BuildingCPP& default_instance();

  void Swap(BuildingCPP* other);

  // implements Message ----------------------------------------------

  BuildingCPP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BuildingCPP& from);
  void MergeFrom(const BuildingCPP& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 ud = 1;
  inline bool has_ud() const;
  inline void clear_ud();
  static const int kUdFieldNumber = 1;
  inline ::google::protobuf::uint32 ud() const;
  inline void set_ud(::google::protobuf::uint32 value);

  // required uint32 buildId = 2;
  inline bool has_buildid() const;
  inline void clear_buildid();
  static const int kBuildIdFieldNumber = 2;
  inline ::google::protobuf::uint32 buildid() const;
  inline void set_buildid(::google::protobuf::uint32 value);

  // repeated uint32 position = 3;
  inline int position_size() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 3;
  inline ::google::protobuf::uint32 position(int index) const;
  inline void set_position(int index, ::google::protobuf::uint32 value);
  inline void add_position(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      position() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_position();

  // required uint32 direct = 4;
  inline bool has_direct() const;
  inline void clear_direct();
  static const int kDirectFieldNumber = 4;
  inline ::google::protobuf::uint32 direct() const;
  inline void set_direct(::google::protobuf::uint32 value);

  // required uint32 doneTime = 5;
  inline bool has_donetime() const;
  inline void clear_donetime();
  static const int kDoneTimeFieldNumber = 5;
  inline ::google::protobuf::uint32 donetime() const;
  inline void set_donetime(::google::protobuf::uint32 value);

  // required uint32 level = 6;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 6;
  inline ::google::protobuf::uint32 level() const;
  inline void set_level(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ProtoBuilding.BuildingCPP)
 private:
  inline void set_has_ud();
  inline void clear_has_ud();
  inline void set_has_buildid();
  inline void clear_has_buildid();
  inline void set_has_direct();
  inline void clear_has_direct();
  inline void set_has_donetime();
  inline void clear_has_donetime();
  inline void set_has_level();
  inline void clear_has_level();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 ud_;
  ::google::protobuf::uint32 buildid_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > position_;
  ::google::protobuf::uint32 direct_;
  ::google::protobuf::uint32 donetime_;
  ::google::protobuf::uint32 level_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static BuildingCPP* default_instance_;
};
// -------------------------------------------------------------------

class EquipmentStarCPP : public ::google::protobuf::Message {
 public:
  EquipmentStarCPP();
  virtual ~EquipmentStarCPP();

  EquipmentStarCPP(const EquipmentStarCPP& from);

  inline EquipmentStarCPP& operator=(const EquipmentStarCPP& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EquipmentStarCPP& default_instance();

  void Swap(EquipmentStarCPP* other);

  // implements Message ----------------------------------------------

  EquipmentStarCPP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EquipmentStarCPP& from);
  void MergeFrom(const EquipmentStarCPP& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required uint32 star = 2;
  inline bool has_star() const;
  inline void clear_star();
  static const int kStarFieldNumber = 2;
  inline ::google::protobuf::uint32 star() const;
  inline void set_star(::google::protobuf::uint32 value);

  // required uint32 usedtime = 3;
  inline bool has_usedtime() const;
  inline void clear_usedtime();
  static const int kUsedtimeFieldNumber = 3;
  inline ::google::protobuf::uint32 usedtime() const;
  inline void set_usedtime(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ProtoBuilding.EquipmentStarCPP)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_star();
  inline void clear_has_star();
  inline void set_has_usedtime();
  inline void clear_has_usedtime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 star_;
  ::google::protobuf::uint32 usedtime_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static EquipmentStarCPP* default_instance_;
};
// -------------------------------------------------------------------

class BuildReq : public ::google::protobuf::Message {
 public:
  BuildReq();
  virtual ~BuildReq();

  BuildReq(const BuildReq& from);

  inline BuildReq& operator=(const BuildReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BuildReq& default_instance();

  void Swap(BuildReq* other);

  // implements Message ----------------------------------------------

  BuildReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BuildReq& from);
  void MergeFrom(const BuildReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 buildId = 1;
  inline bool has_buildid() const;
  inline void clear_buildid();
  static const int kBuildIdFieldNumber = 1;
  inline ::google::protobuf::uint32 buildid() const;
  inline void set_buildid(::google::protobuf::uint32 value);

  // repeated uint32 pos = 2;
  inline int pos_size() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 2;
  inline ::google::protobuf::uint32 pos(int index) const;
  inline void set_pos(int index, ::google::protobuf::uint32 value);
  inline void add_pos(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      pos() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_pos();

  // @@protoc_insertion_point(class_scope:ProtoBuilding.BuildReq)
 private:
  inline void set_has_buildid();
  inline void clear_has_buildid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > pos_;
  ::google::protobuf::uint32 buildid_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static BuildReq* default_instance_;
};
// -------------------------------------------------------------------

class BuildResp : public ::google::protobuf::Message {
 public:
  BuildResp();
  virtual ~BuildResp();

  BuildResp(const BuildResp& from);

  inline BuildResp& operator=(const BuildResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BuildResp& default_instance();

  void Swap(BuildResp* other);

  // implements Message ----------------------------------------------

  BuildResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BuildResp& from);
  void MergeFrom(const BuildResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .ProtoBuilding.BuildingCPP building = 1;
  inline bool has_building() const;
  inline void clear_building();
  static const int kBuildingFieldNumber = 1;
  inline const ::ProtoBuilding::BuildingCPP& building() const;
  inline ::ProtoBuilding::BuildingCPP* mutable_building();
  inline ::ProtoBuilding::BuildingCPP* release_building();
  inline void set_allocated_building(::ProtoBuilding::BuildingCPP* building);

  // required .DataCommon.CommonItemsCPP commons = 2;
  inline bool has_commons() const;
  inline void clear_commons();
  static const int kCommonsFieldNumber = 2;
  inline const ::DataCommon::CommonItemsCPP& commons() const;
  inline ::DataCommon::CommonItemsCPP* mutable_commons();
  inline ::DataCommon::CommonItemsCPP* release_commons();
  inline void set_allocated_commons(::DataCommon::CommonItemsCPP* commons);

  // optional .ProtoProduce.CropLandCPP lands = 3;
  inline bool has_lands() const;
  inline void clear_lands();
  static const int kLandsFieldNumber = 3;
  inline const ::ProtoProduce::CropLandCPP& lands() const;
  inline ::ProtoProduce::CropLandCPP* mutable_lands();
  inline ::ProtoProduce::CropLandCPP* release_lands();
  inline void set_allocated_lands(::ProtoProduce::CropLandCPP* lands);

  // optional .ProtoBuilding.EquipmentStarCPP equipmentstar = 4;
  inline bool has_equipmentstar() const;
  inline void clear_equipmentstar();
  static const int kEquipmentstarFieldNumber = 4;
  inline const ::ProtoBuilding::EquipmentStarCPP& equipmentstar() const;
  inline ::ProtoBuilding::EquipmentStarCPP* mutable_equipmentstar();
  inline ::ProtoBuilding::EquipmentStarCPP* release_equipmentstar();
  inline void set_allocated_equipmentstar(::ProtoBuilding::EquipmentStarCPP* equipmentstar);

  // @@protoc_insertion_point(class_scope:ProtoBuilding.BuildResp)
 private:
  inline void set_has_building();
  inline void clear_has_building();
  inline void set_has_commons();
  inline void clear_has_commons();
  inline void set_has_lands();
  inline void clear_has_lands();
  inline void set_has_equipmentstar();
  inline void clear_has_equipmentstar();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::ProtoBuilding::BuildingCPP* building_;
  ::DataCommon::CommonItemsCPP* commons_;
  ::ProtoProduce::CropLandCPP* lands_;
  ::ProtoBuilding::EquipmentStarCPP* equipmentstar_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static BuildResp* default_instance_;
};
// -------------------------------------------------------------------

class MoveReq : public ::google::protobuf::Message {
 public:
  MoveReq();
  virtual ~MoveReq();

  MoveReq(const MoveReq& from);

  inline MoveReq& operator=(const MoveReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MoveReq& default_instance();

  void Swap(MoveReq* other);

  // implements Message ----------------------------------------------

  MoveReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MoveReq& from);
  void MergeFrom(const MoveReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 ud = 1;
  inline bool has_ud() const;
  inline void clear_ud();
  static const int kUdFieldNumber = 1;
  inline ::google::protobuf::uint32 ud() const;
  inline void set_ud(::google::protobuf::uint32 value);

  // repeated uint32 pos = 2;
  inline int pos_size() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 2;
  inline ::google::protobuf::uint32 pos(int index) const;
  inline void set_pos(int index, ::google::protobuf::uint32 value);
  inline void add_pos(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      pos() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_pos();

  // @@protoc_insertion_point(class_scope:ProtoBuilding.MoveReq)
 private:
  inline void set_has_ud();
  inline void clear_has_ud();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > pos_;
  ::google::protobuf::uint32 ud_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static MoveReq* default_instance_;
};
// -------------------------------------------------------------------

class MoveResp : public ::google::protobuf::Message {
 public:
  MoveResp();
  virtual ~MoveResp();

  MoveResp(const MoveResp& from);

  inline MoveResp& operator=(const MoveResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MoveResp& default_instance();

  void Swap(MoveResp* other);

  // implements Message ----------------------------------------------

  MoveResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MoveResp& from);
  void MergeFrom(const MoveResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline bool result() const;
  inline void set_result(bool value);

  // @@protoc_insertion_point(class_scope:ProtoBuilding.MoveResp)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool result_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static MoveResp* default_instance_;
};
// -------------------------------------------------------------------

class FlipReq : public ::google::protobuf::Message {
 public:
  FlipReq();
  virtual ~FlipReq();

  FlipReq(const FlipReq& from);

  inline FlipReq& operator=(const FlipReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FlipReq& default_instance();

  void Swap(FlipReq* other);

  // implements Message ----------------------------------------------

  FlipReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FlipReq& from);
  void MergeFrom(const FlipReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 ud = 1;
  inline bool has_ud() const;
  inline void clear_ud();
  static const int kUdFieldNumber = 1;
  inline ::google::protobuf::uint32 ud() const;
  inline void set_ud(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ProtoBuilding.FlipReq)
 private:
  inline void set_has_ud();
  inline void clear_has_ud();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 ud_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static FlipReq* default_instance_;
};
// -------------------------------------------------------------------

class FlipResp : public ::google::protobuf::Message {
 public:
  FlipResp();
  virtual ~FlipResp();

  FlipResp(const FlipResp& from);

  inline FlipResp& operator=(const FlipResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FlipResp& default_instance();

  void Swap(FlipResp* other);

  // implements Message ----------------------------------------------

  FlipResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FlipResp& from);
  void MergeFrom(const FlipResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline bool result() const;
  inline void set_result(bool value);

  // @@protoc_insertion_point(class_scope:ProtoBuilding.FlipResp)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool result_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static FlipResp* default_instance_;
};
// -------------------------------------------------------------------

class BuildingUpReq : public ::google::protobuf::Message {
 public:
  BuildingUpReq();
  virtual ~BuildingUpReq();

  BuildingUpReq(const BuildingUpReq& from);

  inline BuildingUpReq& operator=(const BuildingUpReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BuildingUpReq& default_instance();

  void Swap(BuildingUpReq* other);

  // implements Message ----------------------------------------------

  BuildingUpReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BuildingUpReq& from);
  void MergeFrom(const BuildingUpReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 ud = 1;
  inline bool has_ud() const;
  inline void clear_ud();
  static const int kUdFieldNumber = 1;
  inline ::google::protobuf::uint32 ud() const;
  inline void set_ud(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ProtoBuilding.BuildingUpReq)
 private:
  inline void set_has_ud();
  inline void clear_has_ud();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 ud_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static BuildingUpReq* default_instance_;
};
// -------------------------------------------------------------------

class BuildingUpResp : public ::google::protobuf::Message {
 public:
  BuildingUpResp();
  virtual ~BuildingUpResp();

  BuildingUpResp(const BuildingUpResp& from);

  inline BuildingUpResp& operator=(const BuildingUpResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BuildingUpResp& default_instance();

  void Swap(BuildingUpResp* other);

  // implements Message ----------------------------------------------

  BuildingUpResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BuildingUpResp& from);
  void MergeFrom(const BuildingUpResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .DataCommon.CommonItemsCPP commons = 1;
  inline bool has_commons() const;
  inline void clear_commons();
  static const int kCommonsFieldNumber = 1;
  inline const ::DataCommon::CommonItemsCPP& commons() const;
  inline ::DataCommon::CommonItemsCPP* mutable_commons();
  inline ::DataCommon::CommonItemsCPP* release_commons();
  inline void set_allocated_commons(::DataCommon::CommonItemsCPP* commons);

  // @@protoc_insertion_point(class_scope:ProtoBuilding.BuildingUpResp)
 private:
  inline void set_has_commons();
  inline void clear_has_commons();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::DataCommon::CommonItemsCPP* commons_;
  friend void  protobuf_AddDesc_ProtoBuilding_2eproto();
  friend void protobuf_AssignDesc_ProtoBuilding_2eproto();
  friend void protobuf_ShutdownFile_ProtoBuilding_2eproto();

  void InitAsDefaultInstance();
  static BuildingUpResp* default_instance_;
};
// ===================================================================


// ===================================================================

// BuildingCPP

// required uint32 ud = 1;
inline bool BuildingCPP::has_ud() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BuildingCPP::set_has_ud() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BuildingCPP::clear_has_ud() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BuildingCPP::clear_ud() {
  ud_ = 0u;
  clear_has_ud();
}
inline ::google::protobuf::uint32 BuildingCPP::ud() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildingCPP.ud)
  return ud_;
}
inline void BuildingCPP::set_ud(::google::protobuf::uint32 value) {
  set_has_ud();
  ud_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.BuildingCPP.ud)
}

// required uint32 buildId = 2;
inline bool BuildingCPP::has_buildid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BuildingCPP::set_has_buildid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BuildingCPP::clear_has_buildid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BuildingCPP::clear_buildid() {
  buildid_ = 0u;
  clear_has_buildid();
}
inline ::google::protobuf::uint32 BuildingCPP::buildid() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildingCPP.buildId)
  return buildid_;
}
inline void BuildingCPP::set_buildid(::google::protobuf::uint32 value) {
  set_has_buildid();
  buildid_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.BuildingCPP.buildId)
}

// repeated uint32 position = 3;
inline int BuildingCPP::position_size() const {
  return position_.size();
}
inline void BuildingCPP::clear_position() {
  position_.Clear();
}
inline ::google::protobuf::uint32 BuildingCPP::position(int index) const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildingCPP.position)
  return position_.Get(index);
}
inline void BuildingCPP::set_position(int index, ::google::protobuf::uint32 value) {
  position_.Set(index, value);
  // @@protoc_insertion_point(field_set:ProtoBuilding.BuildingCPP.position)
}
inline void BuildingCPP::add_position(::google::protobuf::uint32 value) {
  position_.Add(value);
  // @@protoc_insertion_point(field_add:ProtoBuilding.BuildingCPP.position)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
BuildingCPP::position() const {
  // @@protoc_insertion_point(field_list:ProtoBuilding.BuildingCPP.position)
  return position_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
BuildingCPP::mutable_position() {
  // @@protoc_insertion_point(field_mutable_list:ProtoBuilding.BuildingCPP.position)
  return &position_;
}

// required uint32 direct = 4;
inline bool BuildingCPP::has_direct() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BuildingCPP::set_has_direct() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BuildingCPP::clear_has_direct() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BuildingCPP::clear_direct() {
  direct_ = 0u;
  clear_has_direct();
}
inline ::google::protobuf::uint32 BuildingCPP::direct() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildingCPP.direct)
  return direct_;
}
inline void BuildingCPP::set_direct(::google::protobuf::uint32 value) {
  set_has_direct();
  direct_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.BuildingCPP.direct)
}

// required uint32 doneTime = 5;
inline bool BuildingCPP::has_donetime() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BuildingCPP::set_has_donetime() {
  _has_bits_[0] |= 0x00000010u;
}
inline void BuildingCPP::clear_has_donetime() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void BuildingCPP::clear_donetime() {
  donetime_ = 0u;
  clear_has_donetime();
}
inline ::google::protobuf::uint32 BuildingCPP::donetime() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildingCPP.doneTime)
  return donetime_;
}
inline void BuildingCPP::set_donetime(::google::protobuf::uint32 value) {
  set_has_donetime();
  donetime_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.BuildingCPP.doneTime)
}

// required uint32 level = 6;
inline bool BuildingCPP::has_level() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void BuildingCPP::set_has_level() {
  _has_bits_[0] |= 0x00000020u;
}
inline void BuildingCPP::clear_has_level() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void BuildingCPP::clear_level() {
  level_ = 0u;
  clear_has_level();
}
inline ::google::protobuf::uint32 BuildingCPP::level() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildingCPP.level)
  return level_;
}
inline void BuildingCPP::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.BuildingCPP.level)
}

// -------------------------------------------------------------------

// EquipmentStarCPP

// required uint32 id = 1;
inline bool EquipmentStarCPP::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EquipmentStarCPP::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EquipmentStarCPP::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EquipmentStarCPP::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 EquipmentStarCPP::id() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.EquipmentStarCPP.id)
  return id_;
}
inline void EquipmentStarCPP::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.EquipmentStarCPP.id)
}

// required uint32 star = 2;
inline bool EquipmentStarCPP::has_star() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EquipmentStarCPP::set_has_star() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EquipmentStarCPP::clear_has_star() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EquipmentStarCPP::clear_star() {
  star_ = 0u;
  clear_has_star();
}
inline ::google::protobuf::uint32 EquipmentStarCPP::star() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.EquipmentStarCPP.star)
  return star_;
}
inline void EquipmentStarCPP::set_star(::google::protobuf::uint32 value) {
  set_has_star();
  star_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.EquipmentStarCPP.star)
}

// required uint32 usedtime = 3;
inline bool EquipmentStarCPP::has_usedtime() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EquipmentStarCPP::set_has_usedtime() {
  _has_bits_[0] |= 0x00000004u;
}
inline void EquipmentStarCPP::clear_has_usedtime() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void EquipmentStarCPP::clear_usedtime() {
  usedtime_ = 0u;
  clear_has_usedtime();
}
inline ::google::protobuf::uint32 EquipmentStarCPP::usedtime() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.EquipmentStarCPP.usedtime)
  return usedtime_;
}
inline void EquipmentStarCPP::set_usedtime(::google::protobuf::uint32 value) {
  set_has_usedtime();
  usedtime_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.EquipmentStarCPP.usedtime)
}

// -------------------------------------------------------------------

// BuildReq

// required uint32 buildId = 1;
inline bool BuildReq::has_buildid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BuildReq::set_has_buildid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BuildReq::clear_has_buildid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BuildReq::clear_buildid() {
  buildid_ = 0u;
  clear_has_buildid();
}
inline ::google::protobuf::uint32 BuildReq::buildid() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildReq.buildId)
  return buildid_;
}
inline void BuildReq::set_buildid(::google::protobuf::uint32 value) {
  set_has_buildid();
  buildid_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.BuildReq.buildId)
}

// repeated uint32 pos = 2;
inline int BuildReq::pos_size() const {
  return pos_.size();
}
inline void BuildReq::clear_pos() {
  pos_.Clear();
}
inline ::google::protobuf::uint32 BuildReq::pos(int index) const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildReq.pos)
  return pos_.Get(index);
}
inline void BuildReq::set_pos(int index, ::google::protobuf::uint32 value) {
  pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:ProtoBuilding.BuildReq.pos)
}
inline void BuildReq::add_pos(::google::protobuf::uint32 value) {
  pos_.Add(value);
  // @@protoc_insertion_point(field_add:ProtoBuilding.BuildReq.pos)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
BuildReq::pos() const {
  // @@protoc_insertion_point(field_list:ProtoBuilding.BuildReq.pos)
  return pos_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
BuildReq::mutable_pos() {
  // @@protoc_insertion_point(field_mutable_list:ProtoBuilding.BuildReq.pos)
  return &pos_;
}

// -------------------------------------------------------------------

// BuildResp

// required .ProtoBuilding.BuildingCPP building = 1;
inline bool BuildResp::has_building() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BuildResp::set_has_building() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BuildResp::clear_has_building() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BuildResp::clear_building() {
  if (building_ != NULL) building_->::ProtoBuilding::BuildingCPP::Clear();
  clear_has_building();
}
inline const ::ProtoBuilding::BuildingCPP& BuildResp::building() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildResp.building)
  return building_ != NULL ? *building_ : *default_instance_->building_;
}
inline ::ProtoBuilding::BuildingCPP* BuildResp::mutable_building() {
  set_has_building();
  if (building_ == NULL) building_ = new ::ProtoBuilding::BuildingCPP;
  // @@protoc_insertion_point(field_mutable:ProtoBuilding.BuildResp.building)
  return building_;
}
inline ::ProtoBuilding::BuildingCPP* BuildResp::release_building() {
  clear_has_building();
  ::ProtoBuilding::BuildingCPP* temp = building_;
  building_ = NULL;
  return temp;
}
inline void BuildResp::set_allocated_building(::ProtoBuilding::BuildingCPP* building) {
  delete building_;
  building_ = building;
  if (building) {
    set_has_building();
  } else {
    clear_has_building();
  }
  // @@protoc_insertion_point(field_set_allocated:ProtoBuilding.BuildResp.building)
}

// required .DataCommon.CommonItemsCPP commons = 2;
inline bool BuildResp::has_commons() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BuildResp::set_has_commons() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BuildResp::clear_has_commons() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BuildResp::clear_commons() {
  if (commons_ != NULL) commons_->::DataCommon::CommonItemsCPP::Clear();
  clear_has_commons();
}
inline const ::DataCommon::CommonItemsCPP& BuildResp::commons() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildResp.commons)
  return commons_ != NULL ? *commons_ : *default_instance_->commons_;
}
inline ::DataCommon::CommonItemsCPP* BuildResp::mutable_commons() {
  set_has_commons();
  if (commons_ == NULL) commons_ = new ::DataCommon::CommonItemsCPP;
  // @@protoc_insertion_point(field_mutable:ProtoBuilding.BuildResp.commons)
  return commons_;
}
inline ::DataCommon::CommonItemsCPP* BuildResp::release_commons() {
  clear_has_commons();
  ::DataCommon::CommonItemsCPP* temp = commons_;
  commons_ = NULL;
  return temp;
}
inline void BuildResp::set_allocated_commons(::DataCommon::CommonItemsCPP* commons) {
  delete commons_;
  commons_ = commons;
  if (commons) {
    set_has_commons();
  } else {
    clear_has_commons();
  }
  // @@protoc_insertion_point(field_set_allocated:ProtoBuilding.BuildResp.commons)
}

// optional .ProtoProduce.CropLandCPP lands = 3;
inline bool BuildResp::has_lands() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BuildResp::set_has_lands() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BuildResp::clear_has_lands() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BuildResp::clear_lands() {
  if (lands_ != NULL) lands_->::ProtoProduce::CropLandCPP::Clear();
  clear_has_lands();
}
inline const ::ProtoProduce::CropLandCPP& BuildResp::lands() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildResp.lands)
  return lands_ != NULL ? *lands_ : *default_instance_->lands_;
}
inline ::ProtoProduce::CropLandCPP* BuildResp::mutable_lands() {
  set_has_lands();
  if (lands_ == NULL) lands_ = new ::ProtoProduce::CropLandCPP;
  // @@protoc_insertion_point(field_mutable:ProtoBuilding.BuildResp.lands)
  return lands_;
}
inline ::ProtoProduce::CropLandCPP* BuildResp::release_lands() {
  clear_has_lands();
  ::ProtoProduce::CropLandCPP* temp = lands_;
  lands_ = NULL;
  return temp;
}
inline void BuildResp::set_allocated_lands(::ProtoProduce::CropLandCPP* lands) {
  delete lands_;
  lands_ = lands;
  if (lands) {
    set_has_lands();
  } else {
    clear_has_lands();
  }
  // @@protoc_insertion_point(field_set_allocated:ProtoBuilding.BuildResp.lands)
}

// optional .ProtoBuilding.EquipmentStarCPP equipmentstar = 4;
inline bool BuildResp::has_equipmentstar() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BuildResp::set_has_equipmentstar() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BuildResp::clear_has_equipmentstar() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BuildResp::clear_equipmentstar() {
  if (equipmentstar_ != NULL) equipmentstar_->::ProtoBuilding::EquipmentStarCPP::Clear();
  clear_has_equipmentstar();
}
inline const ::ProtoBuilding::EquipmentStarCPP& BuildResp::equipmentstar() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildResp.equipmentstar)
  return equipmentstar_ != NULL ? *equipmentstar_ : *default_instance_->equipmentstar_;
}
inline ::ProtoBuilding::EquipmentStarCPP* BuildResp::mutable_equipmentstar() {
  set_has_equipmentstar();
  if (equipmentstar_ == NULL) equipmentstar_ = new ::ProtoBuilding::EquipmentStarCPP;
  // @@protoc_insertion_point(field_mutable:ProtoBuilding.BuildResp.equipmentstar)
  return equipmentstar_;
}
inline ::ProtoBuilding::EquipmentStarCPP* BuildResp::release_equipmentstar() {
  clear_has_equipmentstar();
  ::ProtoBuilding::EquipmentStarCPP* temp = equipmentstar_;
  equipmentstar_ = NULL;
  return temp;
}
inline void BuildResp::set_allocated_equipmentstar(::ProtoBuilding::EquipmentStarCPP* equipmentstar) {
  delete equipmentstar_;
  equipmentstar_ = equipmentstar;
  if (equipmentstar) {
    set_has_equipmentstar();
  } else {
    clear_has_equipmentstar();
  }
  // @@protoc_insertion_point(field_set_allocated:ProtoBuilding.BuildResp.equipmentstar)
}

// -------------------------------------------------------------------

// MoveReq

// required uint32 ud = 1;
inline bool MoveReq::has_ud() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MoveReq::set_has_ud() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MoveReq::clear_has_ud() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MoveReq::clear_ud() {
  ud_ = 0u;
  clear_has_ud();
}
inline ::google::protobuf::uint32 MoveReq::ud() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.MoveReq.ud)
  return ud_;
}
inline void MoveReq::set_ud(::google::protobuf::uint32 value) {
  set_has_ud();
  ud_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.MoveReq.ud)
}

// repeated uint32 pos = 2;
inline int MoveReq::pos_size() const {
  return pos_.size();
}
inline void MoveReq::clear_pos() {
  pos_.Clear();
}
inline ::google::protobuf::uint32 MoveReq::pos(int index) const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.MoveReq.pos)
  return pos_.Get(index);
}
inline void MoveReq::set_pos(int index, ::google::protobuf::uint32 value) {
  pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:ProtoBuilding.MoveReq.pos)
}
inline void MoveReq::add_pos(::google::protobuf::uint32 value) {
  pos_.Add(value);
  // @@protoc_insertion_point(field_add:ProtoBuilding.MoveReq.pos)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
MoveReq::pos() const {
  // @@protoc_insertion_point(field_list:ProtoBuilding.MoveReq.pos)
  return pos_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
MoveReq::mutable_pos() {
  // @@protoc_insertion_point(field_mutable_list:ProtoBuilding.MoveReq.pos)
  return &pos_;
}

// -------------------------------------------------------------------

// MoveResp

// required bool result = 1;
inline bool MoveResp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MoveResp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MoveResp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MoveResp::clear_result() {
  result_ = false;
  clear_has_result();
}
inline bool MoveResp::result() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.MoveResp.result)
  return result_;
}
inline void MoveResp::set_result(bool value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.MoveResp.result)
}

// -------------------------------------------------------------------

// FlipReq

// required uint32 ud = 1;
inline bool FlipReq::has_ud() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FlipReq::set_has_ud() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FlipReq::clear_has_ud() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FlipReq::clear_ud() {
  ud_ = 0u;
  clear_has_ud();
}
inline ::google::protobuf::uint32 FlipReq::ud() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.FlipReq.ud)
  return ud_;
}
inline void FlipReq::set_ud(::google::protobuf::uint32 value) {
  set_has_ud();
  ud_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.FlipReq.ud)
}

// -------------------------------------------------------------------

// FlipResp

// required bool result = 1;
inline bool FlipResp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FlipResp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FlipResp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FlipResp::clear_result() {
  result_ = false;
  clear_has_result();
}
inline bool FlipResp::result() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.FlipResp.result)
  return result_;
}
inline void FlipResp::set_result(bool value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.FlipResp.result)
}

// -------------------------------------------------------------------

// BuildingUpReq

// required uint32 ud = 1;
inline bool BuildingUpReq::has_ud() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BuildingUpReq::set_has_ud() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BuildingUpReq::clear_has_ud() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BuildingUpReq::clear_ud() {
  ud_ = 0u;
  clear_has_ud();
}
inline ::google::protobuf::uint32 BuildingUpReq::ud() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildingUpReq.ud)
  return ud_;
}
inline void BuildingUpReq::set_ud(::google::protobuf::uint32 value) {
  set_has_ud();
  ud_ = value;
  // @@protoc_insertion_point(field_set:ProtoBuilding.BuildingUpReq.ud)
}

// -------------------------------------------------------------------

// BuildingUpResp

// required .DataCommon.CommonItemsCPP commons = 1;
inline bool BuildingUpResp::has_commons() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BuildingUpResp::set_has_commons() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BuildingUpResp::clear_has_commons() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BuildingUpResp::clear_commons() {
  if (commons_ != NULL) commons_->::DataCommon::CommonItemsCPP::Clear();
  clear_has_commons();
}
inline const ::DataCommon::CommonItemsCPP& BuildingUpResp::commons() const {
  // @@protoc_insertion_point(field_get:ProtoBuilding.BuildingUpResp.commons)
  return commons_ != NULL ? *commons_ : *default_instance_->commons_;
}
inline ::DataCommon::CommonItemsCPP* BuildingUpResp::mutable_commons() {
  set_has_commons();
  if (commons_ == NULL) commons_ = new ::DataCommon::CommonItemsCPP;
  // @@protoc_insertion_point(field_mutable:ProtoBuilding.BuildingUpResp.commons)
  return commons_;
}
inline ::DataCommon::CommonItemsCPP* BuildingUpResp::release_commons() {
  clear_has_commons();
  ::DataCommon::CommonItemsCPP* temp = commons_;
  commons_ = NULL;
  return temp;
}
inline void BuildingUpResp::set_allocated_commons(::DataCommon::CommonItemsCPP* commons) {
  delete commons_;
  commons_ = commons;
  if (commons) {
    set_has_commons();
  } else {
    clear_has_commons();
  }
  // @@protoc_insertion_point(field_set_allocated:ProtoBuilding.BuildingUpResp.commons)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoBuilding

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtoBuilding_2eproto__INCLUDED
